"""init

Revision ID: 7f4d2fe219f6
Revises: bd78aed20ea0
Create Date: 2025-04-08 18:18:38.397410

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f4d2fe219f6"
down_revision: Union[str, None] = "bd78aed20ea0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "parcel",
        sa.Column("delivery_price", sa.Numeric(precision=8, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parcel", "delivery_price")
    # ### end Alembic commands ###
