"""init

Revision ID: bd78aed20ea0
Revises: aef1c5f1eb9b
Create Date: 2025-04-07 14:06:37.762888

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "bd78aed20ea0"
down_revision: Union[str, None] = "aef1c5f1eb9b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
